# Generated by Django 5.2.8 on 2025-11-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poduct',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=225)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('CountInStock', models.IntegerField()),
                ('CreateAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
