# Generated by Django 5.2.8 on 2025-11-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=225)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('CountInStock', models.IntegerField()),
                ('image', models.ImageField(upload_to='products/')),
                ('CreateAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Poduct',
        ),
    ]
