# Generated by Django 5.2.8 on 2025-11-15 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='CountInStock',
            new_name='countInStock',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='CreateAt',
            new_name='createdAt',
        ),
    ]
